"""P6/R19 §8.3 — FROZEN router reason codes. Changing this set is a policy version bump, never an edit."""

# USE
USE_DIRECT_SYMBOL_MATCH = "USE_DIRECT_SYMBOL_MATCH"
USE_DIRECT_API_MATCH = "USE_DIRECT_API_MATCH"
USE_FAILURE_SIGNATURE_MATCH = "USE_FAILURE_SIGNATURE_MATCH"
USE_VERSION_COMPATIBLE_WORKAROUND = "USE_VERSION_COMPATIBLE_WORKAROUND"
USE_NEW_VERIFIED_ACTION = "USE_NEW_VERIFIED_ACTION"

# ABSTAIN
ABSTAIN_REDUNDANT = "ABSTAIN_REDUNDANT"
ABSTAIN_THEME_ONLY = "ABSTAIN_THEME_ONLY"
ABSTAIN_WRONG_STAGE = "ABSTAIN_WRONG_STAGE"
ABSTAIN_VERSION_MISMATCH = "ABSTAIN_VERSION_MISMATCH"
ABSTAIN_NO_ACTIONABLE_DELTA = "ABSTAIN_NO_ACTIONABLE_DELTA"
ABSTAIN_LOW_MARGIN = "ABSTAIN_LOW_MARGIN"
ABSTAIN_HIGH_RISK = "ABSTAIN_HIGH_RISK"
ABSTAIN_ALREADY_TRIED = "ABSTAIN_ALREADY_TRIED"
ABSTAIN_SCOPE = "ABSTAIN_SCOPE"
ABSTAIN_UNVERIFIED = "ABSTAIN_UNVERIFIED"

USE_CODES = frozenset({
    USE_DIRECT_SYMBOL_MATCH, USE_DIRECT_API_MATCH, USE_FAILURE_SIGNATURE_MATCH,
    USE_VERSION_COMPATIBLE_WORKAROUND, USE_NEW_VERIFIED_ACTION,
})
ABSTAIN_CODES = frozenset({
    ABSTAIN_REDUNDANT, ABSTAIN_THEME_ONLY, ABSTAIN_WRONG_STAGE, ABSTAIN_VERSION_MISMATCH,
    ABSTAIN_NO_ACTIONABLE_DELTA, ABSTAIN_LOW_MARGIN, ABSTAIN_HIGH_RISK, ABSTAIN_ALREADY_TRIED,
    ABSTAIN_SCOPE, ABSTAIN_UNVERIFIED,
})
ALL_CODES = USE_CODES | ABSTAIN_CODES
