"""Service interfaces (§2.1) as async typing Protocols for all external-I/O boundaries. Deterministic,
CPU-only compiler functions stay synchronous (see compiler_ir). Async everywhere else keeps blocking DB /
HTTP / Qdrant / object-store calls off the event loop in the FastAPI + worker paths (P5)."""
from __future__ import annotations
from typing import Protocol, Optional, Any, runtime_checkable


@runtime_checkable
class Registry(Protocol):
    async def get_contract(self, contract_id: str) -> Optional[dict]: ...
    async def put_contract(self, contract: Any) -> str: ...
    async def list_contracts(self, org_id: str | None = None, state: str | None = None) -> list: ...


@runtime_checkable
class MemoryIndex(Protocol):
    async def add_view(self, scope_id: str, memory_id: str, text: str, metadata: dict) -> None: ...
    async def search(self, scope_id: str, query: str, k: int, filters: dict) -> list: ...


class PrivateMemoryIndex(MemoryIndex, Protocol): ...
class SharedMemoryIndex(MemoryIndex, Protocol): ...


@runtime_checkable
class ArtifactStore(Protocol):
    async def put(self, tenant_id: str, key: str, data: bytes, retention_class: str = "default") -> str: ...
    async def get(self, tenant_id: str, key: str) -> bytes: ...


@runtime_checkable
class IdentityProvider(Protocol):
    async def authenticate(self, authorization_header: str | None) -> Any: ...


@runtime_checkable
class RepositoryAuthorizationProvider(Protocol):
    async def can_read(self, ident: Any, repo_id: str) -> bool: ...
    async def can_modify(self, ident: Any, repo_id: str) -> bool: ...
    async def readable_repos(self, ident: Any) -> list: ...


@runtime_checkable
class RepositoryProvider(Protocol):
    async def resolve_commit(self, repo_id: str, ref: str) -> str: ...
    async def snapshot(self, repo_id: str, commit_sha: str, path_allowlist: list) -> dict: ...


@runtime_checkable
class CodingModelProvider(Protocol):
    async def generate(self, logical_request_id: str, prompt: str) -> dict: ...


@runtime_checkable
class SandboxProvider(Protocol):
    async def run(self, snapshot: dict, patch_files: dict, test_entry: str, timeout_s: int) -> dict: ...


@runtime_checkable
class JobRepository(Protocol):
    async def create(self, spec: dict, idempotency_key: str | None = None) -> dict: ...
    async def claim(self, worker_id: str) -> Optional[dict]: ...
    async def transition(self, job_id: str, to_state: str, detail: dict | None = None) -> dict: ...
    async def get(self, job_id: str) -> Optional[dict]: ...


@runtime_checkable
class AuditSink(Protocol):
    async def emit(self, event_type: str, actor: str, subject: str, detail: dict) -> str: ...


@runtime_checkable
class OutcomeStore(Protocol):
    async def persist(self, record: dict) -> str: ...
