"""TRIMEM-CODER memory policy and consolidation primitives.

The package deliberately keeps learned storage advice separate from security and
publication decisions.  A learned policy can choose only between forgetting,
retaining a private episode, and creating a semantic *candidate*.
"""

from .policy import (
    ACTION_ORDER,
    ActionMask,
    DoubleDQNConfig,
    DoubleDQNMemoryPolicy,
    FeatureSchema,
    FrozenCheckpoint,
    MemoryAction,
    MemoryPolicy,
    MemoryState,
    PolicyDecision,
    Transition,
)
from .consolidation import (
    ArchivedEpisode,
    ArchivedSemantic,
    ConsolidationService,
    EpisodeRecord,
    PerUserEpisodicFIFO,
    PromotionReview,
    SemanticMetrics,
    SemanticRecord,
    SemanticStrengthBank,
    add_episode_support,
    candidate_from_episode,
    candidate_from_trusted_document,
    promote_to_organisation,
    semantic_strength,
)
from .schema import (
    DEFAULT_NAMESPACE,
    SCHEMA_VERSION,
    VECTOR_INDEX_SCHEMA_VERSION,
    AccessContext,
    AccessType,
    EdgeType,
    GraphCheckpoint,
    GraphEdge,
    GraphKind,
    GraphNode,
    GraphState,
    LifecycleState,
    MemoryAccessEvent,
    MemoryGraph,
    NodeType,
    OrganisationSemanticGraph,
    PolicyAction,
    PolicyActor,
    PolicyTransition,
    ReviewAuthority,
    ReviewProvenance,
    SemanticStrength,
    SemanticStrengthRecord,
    SemanticSupport,
    ShortTermWorkingGraph,
    TemporalMetadata,
    UserEpisodicGraph,
    UserSemanticGraph,
    VectorIndexMetadata,
    canonical_hash,
    canonical_json,
)
from .store import InMemoryTriMemStore, IntegrityViolation, NotFound, ScopeViolation
from .postgres_store import (
    AppendReceipt,
    CapacityLimits,
    CanonicalReloadError,
    IndexOutboxIntent,
    LifecycleAppendBundle,
    NamespaceClaim,
    NamespaceEvidence,
    PostgresTriMemStore,
    PromotionEvidence,
    SemanticStrengthIncrement,
    SessionCheckpoint,
)
from .vector_index import (
    Qdrant112ClientAdapter,
    QdrantVectorIndexV2,
    VectorIndexProtocol,
    VectorReference,
)
from .production_lifecycle import (
    PostgresDQNExperienceLifecycle,
    ProductionIdentityResolver,
    production_dqn_lifecycle_factory,
)
from .production_v03_lifecycle import (
    PostgresTaskIdentityResolver,
    PostgresV03ExperienceLifecycle,
    production_v03_lifecycle_factory,
)
from .production_promotion import (
    PostgresReviewedPromotionService,
    PromotionError as ProductionPromotionError,
    promotion_review_evidence_hash,
)
from .benchmark_seed import BenchmarkIdentitySeedError, seed_benchmark_identities

__all__ = [
    "SCHEMA_VERSION",
    "VECTOR_INDEX_SCHEMA_VERSION",
    "DEFAULT_NAMESPACE",
    "ACTION_ORDER",
    "AccessContext",
    "AccessType",
    "ActionMask",
    "ArchivedEpisode",
    "ArchivedSemantic",
    "AppendReceipt",
    "BenchmarkIdentitySeedError",
    "CanonicalReloadError",
    "CapacityLimits",
    "ConsolidationService",
    "DoubleDQNConfig",
    "DoubleDQNMemoryPolicy",
    "EdgeType",
    "EpisodeRecord",
    "FeatureSchema",
    "FrozenCheckpoint",
    "GraphCheckpoint",
    "GraphEdge",
    "GraphKind",
    "GraphNode",
    "GraphState",
    "InMemoryTriMemStore",
    "IntegrityViolation",
    "IndexOutboxIntent",
    "LifecycleState",
    "LifecycleAppendBundle",
    "MemoryAccessEvent",
    "MemoryAction",
    "MemoryPolicy",
    "MemoryState",
    "MemoryGraph",
    "NodeType",
    "NamespaceClaim",
    "NamespaceEvidence",
    "NotFound",
    "OrganisationSemanticGraph",
    "PerUserEpisodicFIFO",
    "PolicyDecision",
    "PolicyAction",
    "PolicyActor",
    "PolicyTransition",
    "PostgresTriMemStore",
    "PromotionEvidence",
    "PostgresDQNExperienceLifecycle",
    "PostgresTaskIdentityResolver",
    "PostgresV03ExperienceLifecycle",
    "PostgresReviewedPromotionService",
    "ProductionIdentityResolver",
    "PromotionReview",
    "ProductionPromotionError",
    "ReviewAuthority",
    "ReviewProvenance",
    "ScopeViolation",
    "SemanticMetrics",
    "SemanticRecord",
    "SemanticStrength",
    "SemanticStrengthRecord",
    "SemanticStrengthIncrement",
    "SemanticStrengthBank",
    "SemanticSupport",
    "SessionCheckpoint",
    "ShortTermWorkingGraph",
    "TemporalMetadata",
    "Transition",
    "Qdrant112ClientAdapter",
    "QdrantVectorIndexV2",
    "UserEpisodicGraph",
    "UserSemanticGraph",
    "VectorIndexMetadata",
    "VectorIndexProtocol",
    "VectorReference",
    "add_episode_support",
    "candidate_from_episode",
    "candidate_from_trusted_document",
    "promote_to_organisation",
    "production_dqn_lifecycle_factory",
    "production_v03_lifecycle_factory",
    "promotion_review_evidence_hash",
    "semantic_strength",
    "seed_benchmark_identities",
    "canonical_hash",
    "canonical_json",
]
